version: '3'
services:
  paypay_mongo:

  paypay_backend:
    restart: always
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
      # - 9229:9229
    volumes:
      - './backend:/home/node'
      - '/home/node/node_modules'

  paypay_frontend:
    container_name: paypay_frontend
    restart: always
    environment:
      NODE_ENV: development
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - './frontend:/home/node'
      - '/home/node/node_modules'
    ports:
      - '3000:3000'
      - '9229:9229'
