version: "2"

services:
  db:
    image: postgres:11-alpine
    command: -c fsync=off
    environment:
      POSTGRES_DB: paypay
      POSTGRES_USER: paypay.user
      POSTGRES_PASSWORD: paypay.pass
      TZ: "Asia/Tokyo"
    ports:
      - 5442:5432
    volumes:
      - ./src/database/postgress/data:/var/lib/postgress
      - /etc/postgress/conf.d/my.cnf
      - ./src/database/testing/postgress/sql:/docker-entrypoint-initdb.d
    networks:
      - default_network
  db-test:
    image: postgres:11-alpine
    command: -c fsync=off
    environment:
      POSTGRES_DATABASE: paypay_test
      POSTGRES_USER: paypay.user
      POSTGRES_PASSWORD: paypay.pass
      TZ: "Asia/Tokyo"
    volumes:
      - ./src/database/postgress/data-test:/var/lib/postgress
      - /etc/postgress/conf.d/my.cnf
      - ./src/database/testing/postgress/sql:/docker-entrypoint-initdb.d
    ports:
      - 5452:5432
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
